### ISSUE TITLE
Nothing shown on Field Guide tab?

### ISSUE THREAD

**Issue by superwick** [jmuspratt/craft-fieldguide#5]
Not seeing anything listed on the Field Guide tab in my CP (it just shows the "FieldGuide Dashboard" heading and nothing under it), and I have several fields set up. Not seeing anything in the Chrome console, or any errors in craft/storage/logs/phperrors.log. Anywhere else I can look to help troubleshoot? I've also uninstalled/removed and re-installed to see if that would work.

**Comment by jmuspratt** [comment]
Hmmm, have you added those fields to a section yet? Nothing else comes to mind.

**Comment by superwick** [comment]
Yep. Sections are added and being used in entries. Weird.

**Comment by jmuspratt** [comment]
Darn. I'm not a plugin expert, but I suppose you could try commenting out sections of the plugin code and see if you can get anything to output (using `dump()` if you have to). Or try it on another Craft installation to see if you can target what's different about the problematic one.

**Comment by superwick** [comment]
Well I've tracked down the culprit... the plugin is getting all the data fine. It's just that it's not being displayed because of this CSS in cp.css: 

```css
.grid > .item {
  display: none;   /* here be the culprit */
  padding: 7px;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
```
See the above commit on my fork for fix that worked for me.
